Dz1
EvgeniyQAIT/Otus_Selenium pull request #3
Opened 2024-10-26 14:40 UTC by EvgeniyQAIT

ДЗ "Простые автотесты"

2024-10-30 06:37 UTC, konflic requested changes

2024-10-30 06:37 UTC, konflic commented on conftest.py
> +#
Это что и зачем тут?

2024-10-30 06:37 UTC, konflic commented on conftest.py
> +    if browser_name in ["ch", "chrome"]:
Ну еще бы немного браузеров добавить, иначе непонятно зачем вообще параметр, если все равно один хром.

2024-10-30 06:37 UTC, konflic commented on tests/freepart_test.py
> +#
Зачем?

2024-10-30 06:37 UTC, konflic commented on tests/freepart_test.py
> +
Между фкнциями 2 пустых строки, не больше, не меньше. В пичарме есть встроенный кодстайл, можно хотя бы его запускать.

2024-10-30 06:37 UTC, konflic commented on tests/twopart_test.py
> +    browser.get("http://192.168.0.161:8081/administration/")
Хардкод ip нужно убрать в параметр

2024-11-24 12:35 UTC, closed without merging

2024-11-24 12:35 UTC, EvgeniyQAIT commented
1